apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  replicas: {{.Values.replicaCount}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.container.image}}{{.Values.container.tag}}
        ports:
        - containerPort: {{.Values.container.port}}


---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: {{.Values.name}}
  ports:
    - port: {{.Values.container.port}}
      targetPort: {{.Values.container.port}}
  type: LoadBalancer
